# Generated by Django 2.0.9 on 2019-06-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideax', '0030_auto_20190422_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='init_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
