# Generated by Django 2.0.9 on 2019-05-30 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideax', '0030_auto_20190422_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='init_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='category_dimension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ideax.Category_Dimension'),
        ),
    ]
