# Generated by Django 2.0.9 on 2019-05-31 13:59

from django.db import migrations, models
import ideax.ideax.enums


class Migration(migrations.Migration):

    dependencies = [
        ('ideax', '0031_auto_20190530_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='evaluated',
            field=models.IntegerField(choices=[(ideax.ideax.enums.EvaluationPhase(0), 0), (ideax.ideax.enums.EvaluationPhase(1), 1), (ideax.ideax.enums.EvaluationPhase(2), 2)], default=0),
        ),
    ]
