# Generated by Django 2.0.9 on 2019-06-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideax', '0031_auto_20190605_1420'),
        ('ideax', '0032_idea_evaluated'),
    ]

    operations = [
    ]
