# Generated by Django 2.0.9 on 2019-07-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideax', '0033_merge_20190614_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
