# Generated by Django 2.0.9 on 2019-08-07 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideax', '0035_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idea', to='ideax.Idea')),
                ('idea_related', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related', to='ideax.Idea')),
            ],
        ),
    ]
